/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Produto;
import dao.ConnectionDAO;
import dao.ProdutosDAO;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;

/**
 *
 * @author hyuug
 */
public class CadastroProdutos extends javax.swing.JFrame {
    private ConnectionDAO connection;
    private SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy", Locale.ENGLISH);
    private ProdutosDAO produtosDAO;

    /**
     * Creates new form Agendamento
     */
    public CadastroProdutos(ConnectionDAO connection) {
        this.connection = connection;
        produtosDAO = new ProdutosDAO(connection);
        initComponents();
    }
    private CadastroProdutos(Usuario user) {
        initComponents();
        loggedUser = user;
    }

    public CadastroProdutos getCadastroProdutos(Usuario user){
        if(cadProdSingleton == null){
            cadProdSingleton = new CadastroProdutos(user);
        }

        return cadProdSingleton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        background_ciano = new javax.swing.JPanel();
        label_titulo = new javax.swing.JLabel();
        DadosDoProduto = new javax.swing.JPanel();
        label_codigo = new javax.swing.JLabel();
        label_descricao = new javax.swing.JLabel();
        label_quantidade = new javax.swing.JLabel();
        label_preco = new javax.swing.JLabel();
        label_validade = new javax.swing.JLabel();
        txt_descricao = new javax.swing.JTextField();
        txt_preco = new javax.swing.JTextField();
        txt_codigo = new javax.swing.JTextField();
        txt_qtd = new javax.swing.JTextField();
        txt_validade = new javax.swing.JTextField();
        label_produto = new javax.swing.JLabel();
        txt_produto = new javax.swing.JTextField();
        btn_salvar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_produto = new javax.swing.JTable();
        BarraMenu = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menutItemClientes = new javax.swing.JMenuItem();
        menutItemServicos = new javax.swing.JMenuItem();
        menutItemUsuarios = new javax.swing.JMenuItem();
        menuServicos = new javax.swing.JMenu();
        menutItemAgendamento = new javax.swing.JMenuItem();
        menuVendas = new javax.swing.JMenu();
        menutItemVenderProdutos = new javax.swing.JMenuItem();
        menutItemEstoque = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        menutItemGerarRelatorio = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 245, 245));
        setResizable(false);

        background_ciano.setBackground(new java.awt.Color(0, 204, 204));
        background_ciano.setLayout(null);

        label_titulo.setBackground(new java.awt.Color(0, 204, 204));
        label_titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label_titulo.setForeground(new java.awt.Color(255, 255, 255));
        label_titulo.setText("Cadastro de Produtos");
        background_ciano.add(label_titulo);
        label_titulo.setBounds(200, 30, 390, 48);

        DadosDoProduto.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Produto"));
        DadosDoProduto.setLayout(null);

        label_codigo.setText("Código:");
        DadosDoProduto.add(label_codigo);
        label_codigo.setBounds(30, 50, 60, 16);

        label_descricao.setText("Descrição:");
        DadosDoProduto.add(label_descricao);
        label_descricao.setBounds(30, 100, 70, 16);

        label_quantidade.setText("Quantidade:");
        DadosDoProduto.add(label_quantidade);
        label_quantidade.setBounds(30, 150, 65, 20);

        label_preco.setText("Preço:");
        DadosDoProduto.add(label_preco);
        label_preco.setBounds(500, 150, 60, 20);

        label_validade.setText("Validade:");
        DadosDoProduto.add(label_validade);
        label_validade.setBounds(280, 146, 50, 30);
        DadosDoProduto.add(txt_descricao);
        txt_descricao.setBounds(90, 100, 640, 22);
        DadosDoProduto.add(txt_preco);
        txt_preco.setBounds(540, 150, 190, 22);

        txt_codigo.setBackground(new java.awt.Color(242, 242, 242));
        txt_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoActionPerformed(evt);
            }
        });
        DadosDoProduto.add(txt_codigo);
        txt_codigo.setBounds(90, 50, 150, 22);
        DadosDoProduto.add(txt_qtd);
        txt_qtd.setBounds(110, 150, 130, 22);
        DadosDoProduto.add(txt_validade);
        txt_validade.setBounds(340, 150, 130, 22);

        label_produto.setText("Produto:");
        DadosDoProduto.add(label_produto);
        label_produto.setBounds(280, 50, 60, 16);

        txt_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_produtoActionPerformed(evt);
            }
        });
        DadosDoProduto.add(txt_produto);
        txt_produto.setBounds(330, 50, 400, 22);

        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });
        DadosDoProduto.add(btn_salvar);
        btn_salvar.setBounds(250, 230, 72, 30);

        btn_editar.setText("Editar");
        DadosDoProduto.add(btn_editar);
        btn_editar.setBounds(340, 230, 72, 30);

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        DadosDoProduto.add(btn_cancelar);
        btn_cancelar.setBounds(520, 230, 76, 30);

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });
        DadosDoProduto.add(btn_excluir);
        btn_excluir.setBounds(430, 230, 72, 30);

        tabela_produto.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null},
                        {null, null, null, null, null, null}
                },
                new String [] {
                        "Código", "Nome produto", "Quantidade", "Validade", "Preço", "Descrição"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela_produto);

        DadosDoProduto.add(jScrollPane1);
        jScrollPane1.setBounds(30, 310, 700, 300);

        menuCadastro.setText("Cadastro");

        menutItemClientes.setText("Clientes");
        menutItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutItemClientesActionPerformed(evt);
            }
        });
        menuCadastro.add(menutItemClientes);

        menutItemServicos.setText("Serviços");
        menutItemServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutItemServicosActionPerformed(evt);
            }
        });
        menuCadastro.add(menutItemServicos);

        menutItemUsuarios.setText("Usuários");
        menutItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutItemUsuariosActionPerformed(evt);
            }
        });
        menuCadastro.add(menutItemUsuarios);

        BarraMenu.add(menuCadastro);

        menuServicos.setText("Serviços");

        menutItemAgendamento.setText("Agendamento");
        menuServicos.add(menutItemAgendamento);

        BarraMenu.add(menuServicos);

        menuVendas.setText("Vendas");

        menutItemVenderProdutos.setText("Vender Produtos");
        menutItemVenderProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutItemVenderProdutosActionPerformed(evt);
            }
        });
        menuVendas.add(menutItemVenderProdutos);

        menutItemEstoque.setText("Estoque");
        menuVendas.add(menutItemEstoque);

        BarraMenu.add(menuVendas);

        menuRelatorio.setText("Relatório");

        menutItemGerarRelatorio.setText("Gerar relatório");
        menuRelatorio.add(menutItemGerarRelatorio);

        BarraMenu.add(menuRelatorio);

        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        BarraMenu.add(menuSair);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(background_ciano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(DadosDoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(background_ciano, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DadosDoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 6775, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void menutItemClientesActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void menutItemServicosActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void menutItemVenderProdutosActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void menutItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txt_codigoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txt_produtoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int id;
        try{
            id = Integer.parseInt(txt_codigo.getText());
        }catch (Exception e){
            id = -1;
        }
        String nome = txt_produto.getText();
        String descricao = txt_descricao.getText();
        int quantidade;
        float preco;
        Date dataValidade;
        Produto produto;
        try{
            dataValidade = formatter.parse(txt_validade.getText());
            quantidade = Integer.parseInt(txt_qtd.getText());
            preco = Float.parseFloat(txt_preco.getText());
            produto = new Produto(
                    id, nome, dataValidade, quantidade, preco, descricao
            );
            produtosDAO.inserirProduto(produto);
        }catch(Exception e){
            // Faz validação para o usuario
            // Mostra uma dialogue escrito algo tipo "Os valores entrados foram invalidos, confira
        }
    }

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {
        dispose();
        MenuPrincipal.getMenuPrincipal(loggedUser).setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JPanel DadosDoProduto;
    private javax.swing.JPanel background_ciano;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_codigo;
    private javax.swing.JLabel label_descricao;
    private javax.swing.JLabel label_preco;
    private javax.swing.JLabel label_produto;
    private javax.swing.JLabel label_quantidade;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JLabel label_validade;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuServicos;
    private javax.swing.JMenu menuVendas;
    private javax.swing.JMenuItem menutItemAgendamento;
    private javax.swing.JMenuItem menutItemClientes;
    private javax.swing.JMenuItem menutItemEstoque;
    private javax.swing.JMenuItem menutItemGerarRelatorio;
    private javax.swing.JMenuItem menutItemServicos;
    private javax.swing.JMenuItem menutItemUsuarios;
    private javax.swing.JMenuItem menutItemVenderProdutos;
    private javax.swing.JTable tabela_produto;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_descricao;
    private javax.swing.JTextField txt_preco;
    private javax.swing.JTextField txt_produto;
    private javax.swing.JTextField txt_qtd;
    private javax.swing.JTextField txt_validade;
    // End of variables declaration
}
