/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author hyuug
 */
public class CadastroServico extends javax.swing.JFrame {

    private static CadastroServico cadServSingleton;
    
    // private para restringir o uso do construtor
    private CadastroServico() {
        initComponents();
    }
        
    public static CadastroServico getCadastroServico(){
        if(cadServSingleton == null){
            cadServSingleton = new CadastroServico();
        }
        return cadServSingleton; // retorna instancia
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label_servico = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();
        label_preco = new javax.swing.JLabel();
        txt_servico = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        txt_preco = new javax.swing.JTextField();
        label_descricao = new javax.swing.JLabel();
        txt_descricao = new javax.swing.JTextField();
        btn_novo = new javax.swing.JButton();
        btn_Salvar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        BarraMenu = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menutItemClientes = new javax.swing.JMenuItem();
        menutItemServicos = new javax.swing.JMenuItem();
        menutItemUsuarios = new javax.swing.JMenuItem();
        menuServicos = new javax.swing.JMenu();
        menutItemAgendamento = new javax.swing.JMenuItem();
        menuVendas = new javax.swing.JMenu();
        menutItemVenderProdutos = new javax.swing.JMenuItem();
        menutItemEstoque = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        menutItemGerarRelatorio = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Serviços");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(140, 30, 380, 48);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));
        jPanel1.setLayout(null);

        label_servico.setText("Serviço:");
        jPanel1.add(label_servico);
        label_servico.setBounds(30, 40, 50, 20);

        label_id.setText("ID:");
        jPanel1.add(label_id);
        label_id.setBounds(60, 90, 30, 20);

        label_preco.setText("Preço:");
        jPanel1.add(label_preco);
        label_preco.setBounds(340, 90, 50, 20);
        jPanel1.add(txt_servico);
        txt_servico.setBounds(80, 40, 490, 22);
        jPanel1.add(txt_id);
        txt_id.setBounds(80, 90, 180, 22);
        jPanel1.add(txt_preco);
        txt_preco.setBounds(380, 90, 190, 22);

        label_descricao.setText("Categoria:");
        jPanel1.add(label_descricao);
        label_descricao.setBounds(20, 140, 60, 20);
        jPanel1.add(txt_descricao);
        txt_descricao.setBounds(80, 140, 180, 22);

        btn_novo.setText("+ Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_Salvar.setText("Salvar");

        btn_editar.setText("Editar");

        btn_excluir.setText("Excluir");

        menuCadastro.setText("Cadastro");

        menutItemClientes.setText("Clientes");
        menutItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutItemClientesActionPerformed(evt);
            }
        });
        menuCadastro.add(menutItemClientes);

        menutItemServicos.setText("Serviços");
        menutItemServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutItemServicosActionPerformed(evt);
            }
        });
        menuCadastro.add(menutItemServicos);

        menutItemUsuarios.setText("Usuários");
        menutItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutItemUsuariosActionPerformed(evt);
            }
        });
        menuCadastro.add(menutItemUsuarios);

        BarraMenu.add(menuCadastro);

        menuServicos.setText("Serviços");

        menutItemAgendamento.setText("Agendamento");
        menuServicos.add(menutItemAgendamento);

        BarraMenu.add(menuServicos);

        menuVendas.setText("Vendas");

        menutItemVenderProdutos.setText("Vender Produtos");
        menutItemVenderProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutItemVenderProdutosActionPerformed(evt);
            }
        });
        menuVendas.add(menutItemVenderProdutos);

        menutItemEstoque.setText("Estoque");
        menuVendas.add(menutItemEstoque);

        BarraMenu.add(menuVendas);

        menuRelatorio.setText("Relatório");

        menutItemGerarRelatorio.setText("Gerar relatório");
        menuRelatorio.add(menutItemGerarRelatorio);

        BarraMenu.add(menuRelatorio);

        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        BarraMenu.add(menuSair);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menutItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutItemClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menutItemClientesActionPerformed

    private void menutItemServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutItemServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menutItemServicosActionPerformed

    private void menutItemVenderProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutItemVenderProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menutItemVenderProdutosActionPerformed

    private void menutItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutItemUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menutItemUsuariosActionPerformed

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_novoActionPerformed

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        MenuPrincipal.getMenuPrincipal().setVisible(true);
    }//GEN-LAST:event_menuSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_descricao;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_preco;
    private javax.swing.JLabel label_servico;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuServicos;
    private javax.swing.JMenu menuVendas;
    private javax.swing.JMenuItem menutItemAgendamento;
    private javax.swing.JMenuItem menutItemClientes;
    private javax.swing.JMenuItem menutItemEstoque;
    private javax.swing.JMenuItem menutItemGerarRelatorio;
    private javax.swing.JMenuItem menutItemServicos;
    private javax.swing.JMenuItem menutItemUsuarios;
    private javax.swing.JMenuItem menutItemVenderProdutos;
    private javax.swing.JTextField txt_descricao;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_preco;
    private javax.swing.JTextField txt_servico;
    // End of variables declaration//GEN-END:variables
}
