package View;

import java.awt.BorderLayout;
import javax.swing.JScrollPane;

/**
 *
 * @author paulo
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private static MenuPrincipal menuPrinSingleton;
    
    public MenuPrincipal() {
        initComponents();
        
        /* Tentativa Falha de COlocar imagem e tabela
        
        ImagePanel imagePanel = new ImagePanel("C:/Users/paulo/Documents/MyProjects/ES44B/BarberPro/BarberPro/src/Compromissos do dia.png");
        
        // Defina o ImagePanel como o conteúdo do JFrame
        this.setContentPane(imagePanel);
        
        imagePanel.setLayout(new BorderLayout());
        imagePanel.add(new JScrollPane(tab_Horarios), BorderLayout.CENTER);
        */
    }
    
    public static MenuPrincipal getMenuPrincipal(){
        if(menuPrinSingleton == null){
            menuPrinSingleton = new MenuPrincipal();
        }
        return menuPrinSingleton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tab_Horarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuItemCliente = new javax.swing.JMenuItem();
        menuItemUsuario = new javax.swing.JMenuItem();
        menuItemServico = new javax.swing.JMenuItem();
        menuServicos = new javax.swing.JMenu();
        menuItemAgendamento = new javax.swing.JMenuItem();
        menuVendas = new javax.swing.JMenu();
        menuItemVender = new javax.swing.JMenuItem();
        menuItemEstoque = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuItemRelatorio = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 823));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setOpaque(false);

        tab_Horarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Servico", "Data", "Horário", "Barbeiro"
            }
        ));
        tab_Horarios.setOpaque(false);
        jScrollPane1.setViewportView(tab_Horarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 590, 470));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Compromissos do dia (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        menuCadastro.setText("Cadastro");

        menuItemCliente.setText("Cliente");
        menuCadastro.add(menuItemCliente);

        menuItemUsuario.setText("Usuário");
        menuCadastro.add(menuItemUsuario);

        menuItemServico.setText("Serviço");
        menuCadastro.add(menuItemServico);

        jMenuBar1.add(menuCadastro);

        menuServicos.setText("Serviços");

        menuItemAgendamento.setText("Agendamento");
        menuServicos.add(menuItemAgendamento);

        jMenuBar1.add(menuServicos);

        menuVendas.setText("Vendas");

        menuItemVender.setText("Vender Produtos");
        menuVendas.add(menuItemVender);

        menuItemEstoque.setText("Estoque");
        menuVendas.add(menuItemEstoque);

        jMenuBar1.add(menuVendas);

        menuRelatorios.setText("Relatórios");

        menuItemRelatorio.setText("Gerar Relatório");
        menuRelatorios.add(menuItemRelatorio);

        jMenuBar1.add(menuRelatorios);

        menuSair.setText("Sair");
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuItemAgendamento;
    private javax.swing.JMenuItem menuItemCliente;
    private javax.swing.JMenuItem menuItemEstoque;
    private javax.swing.JMenuItem menuItemRelatorio;
    private javax.swing.JMenuItem menuItemServico;
    private javax.swing.JMenuItem menuItemUsuario;
    private javax.swing.JMenuItem menuItemVender;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuServicos;
    private javax.swing.JMenu menuVendas;
    private javax.swing.JTable tab_Horarios;
    // End of variables declaration//GEN-END:variables
}
