
 // Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 // Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template

package View;

/**
 *
 * @author hyuug
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Agendamento
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BarraMenu = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menutItemClientes = new javax.swing.JMenuItem();
        menutItemServicos = new javax.swing.JMenuItem();
        menutItemUsuarios = new javax.swing.JMenuItem();
        menuServicos = new javax.swing.JMenu();
        menutItemAgendamento = new javax.swing.JMenuItem();
        menuVendas = new javax.swing.JMenu();
        menutItemVenderProdutos = new javax.swing.JMenuItem();
        menutItemEstoque = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        menutItemGerarRelatorio = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Compromissos do dia");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Serviço", "Data", "Horário", "Barbeiro"
            }
        ));
        jScrollPane1.setViewportView(jTable1);


        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Compromissos do dia (1).png"))); // NOI18N

        menuCadastro.setText("Cadastro");

        menutItemClientes.setText("Clientes");
        menutItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutItemClientesActionPerformed(evt);
            }
        });
        menuCadastro.add(menutItemClientes);

        menutItemServicos.setText("Serviços");
        menutItemServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutItemServicosActionPerformed(evt);
            }
        });
        menuCadastro.add(menutItemServicos);

        menutItemUsuarios.setText("Usuários");
        menutItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutItemUsuariosActionPerformed(evt);
            }
        });
        menuCadastro.add(menutItemUsuarios);

        BarraMenu.add(menuCadastro);

        menuServicos.setText("Serviços");

        menutItemAgendamento.setText("Agendamento");
        menuServicos.add(menutItemAgendamento);

        BarraMenu.add(menuServicos);

        menuVendas.setText("Vendas");

        menutItemVenderProdutos.setText("Vender Produtos");
        menutItemVenderProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menutItemVenderProdutosActionPerformed(evt);
            }
        });
        menuVendas.add(menutItemVenderProdutos);

        menutItemEstoque.setText("Estoque");
        menuVendas.add(menutItemEstoque);

        BarraMenu.add(menuVendas);

        menuRelatorio.setText("Relatório");

        menutItemGerarRelatorio.setText("Gerar relatório");
        menuRelatorio.add(menutItemGerarRelatorio);

        BarraMenu.add(menuRelatorio);

        menuSair.setText("Sair");
        BarraMenu.add(menuSair);

        setJMenuBar(BarraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menutItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutItemClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menutItemClientesActionPerformed

    private void menutItemServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutItemServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menutItemServicosActionPerformed

    private void menutItemVenderProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutItemVenderProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menutItemVenderProdutosActionPerformed

    private void menutItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menutItemUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menutItemUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuServicos;
    private javax.swing.JMenu menuVendas;
    private javax.swing.JMenuItem menutItemAgendamento;
    private javax.swing.JMenuItem menutItemClientes;
    private javax.swing.JMenuItem menutItemEstoque;
    private javax.swing.JMenuItem menutItemGerarRelatorio;
    private javax.swing.JMenuItem menutItemServicos;
    private javax.swing.JMenuItem menutItemUsuarios;
    private javax.swing.JMenuItem menutItemVenderProdutos;
    // End of variables declaration//GEN-END:variables
}
