
 // Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 // Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template

package View;

/**
 *
 * @author hyuug
 */
public class MenuPrincipal extends javax.swing.JFrame {

    // var para receber a instancia
    private static MenuPrincipal MenuSingleton;
    
    // private para restringir o uso do construtor
    private MenuPrincipal() {
        initComponents();
    }
    
    // Singleton para evitar duas múltiplas instâncias
    public static MenuPrincipal getMenuPrincipal(){
        if(MenuSingleton == null){
            MenuSingleton = new MenuPrincipal();
        }
        return MenuSingleton;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lab_Compromissos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_Compromissos = new javax.swing.JTable();
        img_Fundo = new javax.swing.JLabel();
        BarraMenu = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menutItemClientes = new javax.swing.JMenuItem();
        menutItemServicos = new javax.swing.JMenuItem();
        menutItemUsuarios = new javax.swing.JMenuItem();
        menuServicos = new javax.swing.JMenu();
        menutItemAgendamento = new javax.swing.JMenuItem();
        menuVendas = new javax.swing.JMenu();
        menutItemVenderProdutos = new javax.swing.JMenuItem();
        menutItemEstoque = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        menutItemGerarRelatorio = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lab_Compromissos.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        lab_Compromissos.setForeground(new java.awt.Color(255, 255, 255));
        lab_Compromissos.setText("Compromissos do dia");

        tab_Compromissos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Serviço", "Data", "Horário", "Barbeiro"
            }
        ));
        jScrollPane1.setViewportView(tab_Compromissos);

        img_Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Compromissos do dia (1).png"))); // NOI18N

        menuCadastro.setText("Cadastro");
        

        menutItemClientes.setText("Clientes");
        
        
        menuCadastro.add(menutItemClientes);

        menutItemServicos.setText("Serviços");
        
        menuCadastro.add(menutItemServicos);

        menutItemUsuarios.setText("Usuários");
        
        
        menuCadastro.add(menutItemUsuarios);

        BarraMenu.add(menuCadastro);

        menuServicos.setText("Serviços");

        menutItemAgendamento.setText("Agendamento");
        menuServicos.add(menutItemAgendamento);

        BarraMenu.add(menuServicos);

        menuVendas.setText("Vendas");

        menutItemVenderProdutos.setText("Vender Produtos");
        
        menuVendas.add(menutItemVenderProdutos);

        menutItemEstoque.setText("Estoque");
        menuVendas.add(menutItemEstoque);

        BarraMenu.add(menuVendas);

        menuRelatorio.setText("Relatório");

        menutItemGerarRelatorio.setText("Gerar relatório");
        menuRelatorio.add(menutItemGerarRelatorio);

        BarraMenu.add(menuRelatorio);

        menuSair.setText("Sair");
        
        BarraMenu.add(menuSair);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(640, 640, 640)
                .addComponent(lab_Compromissos))
            .addComponent(img_Fundo)
            .addGroup(layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(lab_Compromissos))
            .addComponent(img_Fundo, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menutItemClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menutItemClientesMouseClicked
        
        CadastroClientes.getCadastroClientes().setVisible(true);
        
    }//GEN-LAST:event_menutItemClientesMouseClicked

    private void menutItemUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menutItemUsuariosMouseClicked
        CadastroUsuarios.getCadastroUsuarios().setVisible(true);
    }//GEN-LAST:event_menutItemUsuariosMouseClicked

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        dispose();
    }//GEN-LAST:event_menuSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JLabel img_Fundo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lab_Compromissos;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuServicos;
    private javax.swing.JMenu menuVendas;
    private javax.swing.JMenuItem menutItemAgendamento;
    private javax.swing.JMenuItem menutItemClientes;
    private javax.swing.JMenuItem menutItemEstoque;
    private javax.swing.JMenuItem menutItemGerarRelatorio;
    private javax.swing.JMenuItem menutItemServicos;
    private javax.swing.JMenuItem menutItemUsuarios;
    private javax.swing.JMenuItem menutItemVenderProdutos;
    private javax.swing.JTable tab_Compromissos;
    // End of variables declaration//GEN-END:variables
}
